Application\Sonata\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        username:
          expose: true
        username_canonical:
          expose: false
        email:
          expose: false
        email_canonical:
          expose: false
        enabled:
          expose: false
        locked:
          expose: false
        expired:
          expose: false
        roles:
          expose: false
        credentials_expired:
          expose: false
        created_at:
          expose: false
        updated_at:
          expose: false
        gender:
          expose: false
        id:
          expose: false
        questions:
          expose: false
        speaker:
          expose: false
        avatar:
          expose: false
