fos_comment:
    db_driver: orm
    class:
        model:
            comment: Dwl\Exim\CoreBundle\Entity\Comment\Comment
            thread:  Dwl\Exim\CoreBundle\Entity\Comment\Thread
    form:
        comment:
            type: sonata_comment_comment
