<?php

namespace Dwl\LexBundle\Repository;

/**
 * AuthoritySupremeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthoritySupremeRepository extends \Doctrine\ORM\EntityRepository
{
}
