<?php

namespace Dwl\LexBundle\Repository;

/**
 * DictumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictumRepository extends \Doctrine\ORM\EntityRepository
{
}
