# dependencies :
#    - sonata-porject
#    - liip/imagine-bundle
#    - liip/imagine-bundle
#    - knplabs/knp-gaufrette-bundle

parameters:
    # theme details
    theme.name: lcdd
    theme.path.root: '%kernel.root_dir%/../web/themes/%theme.name%'
    theme.path.web: '/themes/%theme.name%'
    theme.path.public: 'bundles/dwleximcore/themes/%theme.name%'
    theme.path.internal: '%kernel.root_dir%/../web/%theme.path.public%'
    theme.path.private: 'DwlEximCoreBundle:themes/%theme.name%'
    theme.assets.version: '1.0'

    # Assetic
    # assetic.filter.compass.images_dir: '%kernel.root_dir%/../web/images'
    # assetic.filter.compass.http_path:  '/images'


twig:
    paths:
        '%kernel.root_dir%/../web/themes/%theme.name%/views': '%theme.name%'
    globals:
        theme:
            name: '%theme.name%'
            path:
                web:     '%theme.path.web%'
                root:    '%theme.path.root%'
                public:  '%theme.path.public%'
                private: '%theme.path.private%'
            assets:
                version: '%theme.assets.version%'
                javascripts:
                    - //maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
                    - bundles/sonatapage/sonata-page.front.js

assetic:

    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    write_to:       %kernel.root_dir%/../web/themes/%theme.name%
    filters:
        cssrewrite:
            style: compressed
        sass:
            bin: /usr/local/bin/sass
            apply_to:   '\.sass$'
            style: compressed
        compass:
            bin: /usr/local/bin/compass
            apply_to:   '\.scss$'
            style: compressed

    assets:
        front_css:
            inputs:
                - //maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
                - %theme.path.root%/assets/css/sonata_legacy.css
                - %theme.path.root%/assets/css/lcdd.css
                - %theme.path.root%/assets/compass/scss/front.scss
                - %theme.path.root%/assets/compass/scss/style.scss
            output: 'assets/css/front.css'
        # front_js:
        #     inputs:
        #     output: 'assets/css/front.js'


# http://www.reussir-mon-ecommerce.fr/2012/08/15/manipuler-les-images-avec-symfony2-et-liipimaginebundle/
# https://www.youtube.com/watch?v=8QUam-fBtd0
# https://www.opensky.com/
# http://www.slideshare.net/kriswallsmith/introducing-assetic-asset-management-for-php-53
liip_imagine:
    resolvers:
        theme:
            web_path:
                web_root: '%kernel.root_dir%/../web'
                cache_prefix: '%theme.path.web%/assets/img'
    loaders:
        theme:
            filesystem:
                data_root: '%theme.path.root%/media'
    cache:                theme
    data_loader:          theme
    filter_sets:
        src: ~
        thumb:
            filters:
                thumbnail:
                    size: [120, 90]
                    mode: outbound
                background:
                    size: [124, 94]
                    position: center
                    color: '#000000'

# knp_gaufrette:
#     adapters:
#         media:
#             local:
#                 directory: '%kernel.root_dir%/../web'
#     filesystems:
#             media:
#                 adapter:    media
#                 alias:      media_filesystem
