doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataBasketBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    ApplicationSonataNewsBundle: ~
                    ApplicationSonataProductBundle: ~
                    SonataSeoBundle: ~


stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true
            timestampable: false # not needed: listeners are not enabled by default

# services:
#   dwl.helper.globalHelper:
#     class: Dwl\Exim\CoreBundle\Helper\globalHelper
#     arguments: ['@service_container']
