doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataBasketBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    ApplicationSonataNewsBundle: ~
                    ApplicationSonataProductBundle: ~
                    SonataSeoBundle: ~


