cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            # cmf_routing.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
    # class:
    #     site:     Application\Sonata\PageBundle\Entity\Site
    #     snapshot: Application\Sonata\PageBundle\Entity\Snapshot
    #     page:     Application\Sonata\PageBundle\Entity\Page
    #     block:    Application\Sonata\PageBundle\Entity\Block
    # default_template: default
    templates:
        global:
            path: '@theme/Template/global.html.twig'
            name: 'Global layout'
            containers:
                header:
                    name: En-tete
                header_connexion:
                    name: Header connexion
                header_top:
                    name: Header Top
                header_menu:
                    name: Header Menu
                content_search:
                    name: Home Search
                content_top:
                    name: Content Top
                content:
                    name: Content
                content_bottom:
                    name: Content Bottom
                bottom_newsletter:
                    name: Bottom Newsletter
                bottom_embed:
                    name: Bottom Embed
                footer:
                    name: Pied de page
            matrix:
                 layout: |
                     HHHHHHHH
                     KKKKKKKK
                     cccccccc
                     MMMMSSSS
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                     NNNNEEEE
                     FFFFFFFF

                 mapping:
                    H: header
                    c: header_connexion
                    K: header_top
                    M: header_menu
                    S: content_search
                    T: content_top
                    C: content
                    B: content_bottom
                    N: bottom_newsletter
                    E: bottom_embed
                    F: footer

        default:
            path: '@theme/Template/default.html.twig'
            name: 'Default layout - default'
            containers:
                 content:
                     name: Main content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                     CCCCCCCC
                     FFFFFFFF

                 mapping:
                     C: content
                     F: footer

        index:
            path: '@theme/Template/index.html.twig'
            name: 'Index layout - default'
            containers:
                 content_search:
                     name: Moteur de recherche
                 content_concept:
                     name: Concept
                 content_video:
                     name: Videos
                 content_question:
                     name: Questions
                 content_category:
                     name: Questions
                 content_person:
                     name: Intervenants
            matrix:
                 layout: |
                     ssssssssssss
                     iiiiiiiiiiii
                     vvvvvvvvvvvv
                     qqqqqqqqqqqq
                     cccccccccccc
                     pppppppppppp

                 mapping:
                     s: content_search
                     i: content_concept
                     v: content_video
                     q: content_question
                     c: content_category
                     p: content_person

        # 2columns:
        #     path: '@theme/Template/index.html.twig'
        #     name: '2 columns layout'
        #     containers:
        #          header:
        #              name: Header
        #          content_search:
        #              name: Home Search
        #          footer:
        #              name: Footer
        #     matrix:
        #          layout: |
        #              HHHHHHHH
        #              SSSSSSSS
        #              FFFFFFFF

        #          mapping:
        #              H: header
        #              S: content_search
        #              F: footer

    templates_admin:
        compose:                    SonataPageBundle:PageAdmin:compose.html.twig

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataPageBundle: ~


