security:
    role_hierarchy:
        ROLE_EXIM_USER:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_USER_ADMIN_USER_SPEAKER
            - ROLE_SONATA_CUSTOMER_ADMIN_CUSTOMER_SPEAKER
            - ROLE_DWL_LCDD_SPEAKER_SPEAKER_SPEAKER
        ROLE_LCDD_SPEAKER:
            - ROLE_EXIM_USER
        ROLE_ADMIN:
            - ROLE_LCDD_SPEAKER
        ROLE_SUPER_ADMIN:
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT
        ROLE_EXIM_ADMIN: ROLE_SUPER_ADMIN

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # It also secures the shop checkout process
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_EXIM_USER] }
        - { path: ^/profile/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/shop/basket/step/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/shop/user/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

