dwl_exim_core_private_views:
    path:     /themes/[^/]+/views
    defaults: { _controller: DwlEximCoreBundle:Default:index }
dwl_exim_core_private_assets:
    path:     /themes/[^/]+/assets
    defaults: { _controller: DwlEximCoreBundle:Default:index }
dwl_exim_core_private_src:
    path:     /themes/[^/]+/src
    defaults: { _controller: DwlEximCoreBundle:Default:index }

dwl_exim_core_homepage:
    path:     /exim/{name}
    defaults: { _controller: DwlEximCoreBundle:Default:index }
