# Enable Doctrine to map the provided entities
sonata_invoice:
    class:
        invoice:         Application\Sonata\InvoiceBundle\Entity\Invoice
        invoice_element: Application\Sonata\InvoiceBundle\Entity\InvoiceElement
        customer:        Application\Sonata\CustomerBundle\Entity\Customer
        order_element:   Application\Sonata\OrderBundle\Entity\OrderElement

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataInvoiceBundle: ~
