sonata_basket:
    class:
        basket:         Application\Sonata\BasketBundle\Entity\Basket
        basket_element: Application\Sonata\BasketBundle\Entity\BasketElement
        customer:       Dwl\Exim\CoreBundle\Entity\Commerce\Customer

    builder:            sonata.basket.builder.standard
    factory:            sonata.basket.entity.factory
    loader:             sonata.basket.loader.standard

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataBasketBundle: ~
