# Enable Doctrine to map the provided entities
sonata_customer:
    class:
        customer: Dwl\Exim\CoreBundle\Entity\Commerce\Customer
        address:  Dwl\Exim\CoreBundle\Entity\Commerce\Address
        order:    Dwl\Exim\CoreBundle\Entity\Commerce\Order
        user:     Dwl\Exim\CoreBundle\Entity\User\User

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataCustomerBundle: ~
