sonata_classification:
    class:
        tag:            Dwl\Exim\CoreBundle\Entity\Classification\Tag
        category:       Dwl\Exim\CoreBundle\Entity\Classification\Category
        context:        Dwl\Exim\CoreBundle\Entity\Classification\Context
        collection:     Dwl\Exim\CoreBundle\Entity\Classification\Collection
        media:          Dwl\Exim\CoreBundle\Entity\Media\Media

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
