# Enable Doctrine to map the provided entities
sonata_invoice:
    class:
        invoice:         Dwl\Exim\CoreBundle\Entity\Commerce\Invoice
        invoice_element: Dwl\Exim\CoreBundle\Entity\Commerce\InvoiceElement
        customer:        Dwl\Exim\CoreBundle\Entity\Commerce\Customer
        order_element:   Dwl\Exim\CoreBundle\Entity\Commerce\OrderElement

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataInvoiceBundle: ~
