# Enable Doctrine to map the provided entities
sonata_order:
    class:
        order:         Dwl\Exim\CoreBundle\Entity\Commerce\Order
        order_element: Dwl\Exim\CoreBundle\Entity\Commerce\OrderElement
        customer:      Dwl\Exim\CoreBundle\Entity\Commerce\Customer

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataOrderBundle: ~
