#
# more information can be found here https://sonata-project.org/bundles/comment
#
sonata_comment:
    manager_type: orm # can be 'orm' or 'mongodb'
    class:
        comment:  Dwl\Exim\CoreBundle\Entity\Comment\Comment # This is an optional value
        thread:   Dwl\Exim\CoreBundle\Entity\Comment\Thread   # This is an optional value
        category: Dwl\Exim\CoreBundle\Entity\Classification\Category   # This is an optional value
