<?php

namespace Dwl\Lcdd\SearchBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Dwl\Lcdd\SearchBundle\Entity\QuestionCategory;

/**
 * QuestionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCategoryRepository extends EntityRepository
{
}
