<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Application\Sonata\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    const LCDD_ID = 31;

    public function findLcdd() {
        return $this->findOneById(self::LCDD_ID);
    }


    public function findLikeByUsername($username) {

        $us = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from('\Application\Sonata\UserBundle\Entity\User', 'u')
            ->where('u.username LIKE :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->getResult();

        return $us;
    }

    public function findAllAsArray() {

        $us = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u', 'q')
            ->from('\Application\Sonata\UserBundle\Entity\User', 'u')
            ->leftJoin('u.questions', 'q')
            ->getQuery()
            ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        return $us;
    }

    public function findAll() {

        return $this->findBy(array(), array(
            'lastname' => 'ASC',
            'firstname' => 'ASC',
            'username' => 'ASC',
        ));

    }

    public function findUsersByGroupId($id) {

        $speakers = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u', 'g')
            ->from('\Application\Sonata\UserBundle\Entity\User', 'u')
            ->LeftJoin('u.groups', 'g')
            ->where('g.id IN (:groupIds)')
            ->setParameter('groupIds', $id)
            ->orderBy('u.lastname, u.firstname, u.username')
            ->getQuery()
            ->getResult();

        return $speakers;

    }
}
