parameters:
    legi.elastic.host: ''
    legi.elastic.port: ''
    legi.elastic.request: ''
    legi.elastic.index: ''
twig:
    paths:
        '%exim.lcdd.search.resources%/views': views
    globals:
        lcdd:
            elastic:
                host: '%lcdd.elastic.host%'
                port: '%lcdd.elastic.port%'
                request: '%lcdd.elastic.request%'
                index: '%lcdd.elastic.index%'
        legi:
            elastic:
                host: '%legi.elastic.host%'
                port: '%legi.elastic.port%'
                request: '%legi.elastic.request%'
                index: '%legi.elastic.index%'
            search:
                host: '%lcdd.search.host%'
                port: '%lcdd.search.port%'
                request: '%lcdd.search.request%'
