parameters:
  dwl.lcdd.search.question.admin.question.class: 'Dwl\Lcdd\SearchBundle\Admin\QuestionAdmin'
  dwl.lcdd.search.question.admin.question.entity: 'Dwl\Lcdd\SearchBundle\Entity\Question'
  dwl.lcdd.search.question.admin.question.controller: 'SonataAdminBundle:CRUD'

services:
    dwl.lcdd.search.question:
        class: '%dwl.lcdd.search.question.admin.question.class%'
        tags:
            -
              name: sonata.admin
              manager_type: orm
              group: Lcdd
              label: Questions
              show_in_dashboard: false
              label: question
              label_translator_strategy: sonata.admin.label.strategy.underscore
        arguments: ['', '%dwl.lcdd.search.question.admin.question.entity%', '%dwl.lcdd.search.question.admin.question.controller%']
