dwl_lcdd_search_question_submit:
    path:     /lcdd/question/submit
    methods:
        - POST
    defaults:
        _controller: DwlLcddSearchBundle:Question:Submit
        qualified: false
    requirements:
        question: .+
        qualified: true|false
        _locale: fr
    options:
        expose: true

dwl_lcdd_search_question:
    path:     /recherche
    defaults:
        _controller: DwlLcddSearchBundle:Question:Search
    requirements:
        question: .*
        _locale: fr
    options:
        expose: true

dwl_lcdd_question:
    path:     /question/{id}
    defaults:
        _controller: DwlLcddSearchBundle:Question:Show
    requirements:
        id: \d+
        _locale: fr
    options:
        expose: true

