<?php

namespace Dwl\I18nBundle\Repository;

/**
 * DictumTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictumTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
