<?php

namespace Dwl\I18nBundle\Repository;

/**
 * SourceTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
