# dependencies :
#    - sonata-porject
#    - liip/imagine-bundle
#    - knplabs/knp-gaufrette-bundle
# configuration :
#    - exim config & appKernel need to be called after all other bundles and before app bundles

parameters:
    # theme details

    # Sonata Admin Options
    exim_admin.title: 'La chaine du droit'
    exim_admin.logo_title: '%exim.theme.path.web%/media/images/icon-full.png'

    # Sonata Seo Options
    exim_seo.title: 'La Chainde du Droit'
    exim_seo.baseline: 'Comprendre le droit'

    exim.theme.name: lcdd
    exim.theme.host: dev.lachainedudroit.fr
    exim.theme.assets.version.css: '1.0'
    exim.theme.assets.version.js: '1.0'
    exim.theme.assets.version.img: '1.0'
    exim.theme.front.css:
        - '%exim.theme.path.root%/assets/legacy/compass/scss/sonata_legacy.scss'
        - '%exim.theme.path.root%/assets/compass/scss/front_admin.scss'
        - '%exim.theme.path.root%/assets/compass/scss/style.scss'
    exim.theme.admin.css:
        - 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
        - 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    exim.theme.front.js: []

    exim.theme.vendor_front.css:
        - 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
        - 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    exim.theme.vendor_front.js:
        - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js'
        - 'https://cdnjs.cloudflare.com/ajax/libs/sizzle/2.2.0/sizzle.min.js'
        - 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'

        # lcdd bundle
        - '//code.angularjs.org/1.2.16/angular.js'
        - '//code.angularjs.org/1.2.25/angular-sanitize.js'
        - '/bundles/dwllcddsearch/vendor/elastic.js/dist/elastic.min.js'

    exim.theme.front.css.extra:
        - 'front'
        - 'front_lcdd'
    exim.theme.front.js.extra:
        - 'sonata_front_js'
        - 'front_lcdd'

    exim.theme.front.css.vendor: '%exim.theme.vendor_front.css%'
    exim.theme.front.js.vendor: '%exim.theme.vendor_front.js%'

    exim.theme.admin.skin: 'skin-blue-light'

    # Assetic
    # assetic.filter.compass.images_dir: '%kernel.root_dir%/../web/images'
    # assetic.filter.compass.http_path:  '/images'
