<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\CustomerBundle\Entity;

use Sonata\CustomerBundle\Entity\BaseCustomer as BaseCustomer;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Customer extends BaseCustomer
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function setFirstname($firstname)
    {

        if(!empty($this->user)) {
            $this->user->setFirstname($firstname);
        }

        $this->firstname = $firstname;
    }

    /**
     * {@inheritdoc}
     */
    public function getFirstname()
    {

        $firstname = '';

        if(!empty($this->user)) {
            $firstname = $this->user->getFirstname();
        }
        if(empty($firstname)) {
            $firstname = $this->firstname;
        }

        return $firstname;

    }

    /**
     * {@inheritdoc}
     */
    public function setLastname($lastname)
    {
        if(!empty($this->user)) {
            $this->user->setLastname($lastname);
        }

        $this->lastname = $lastname;
    }

    /**
     * {@inheritdoc}
     */
    public function getLastname()
    {

        $lastname = '';

        if(!empty($this->user)) {
            $lastname = $this->user->getLastname();
        }
        if(empty($lastname)) {
            $lastname = $this->lastname;
        }

        return $lastname;

    }

    /**
     * {@inheritdoc}
     */
    public function getFullname()
    {

        $fullname = trim($this->getFirstname().' '.$this->getLastname());

        if(empty($fullname)) {
            if(!empty($this->user)) {
                $fullname = trim($this->user->getUsername());
            }
            if(!empty($this->user)) {
                $fullname = trim("-");
            }
        }

        return ucfirst($fullname);

    }


}
