fos_user_change_password:
  path: "/change-password"
  methods: [GET,POST]
  defaults:
    _controller: ApplicationSonataUserBundle:ChangePasswordFOSUser1:changePassword

sonata_user_change_password:
  path: "/change-password"
  methods: [GET,POST]
  defaults:
    _controller: ApplicationSonataUserBundle:ChangePasswordFOSUser1:changePassword
