fos_user_change_password:
  path: "/change-password.{_format}"
  methods: [GET,POST]
  defaults:
    _controller: ApplicationSonataUserBundle:ChangePasswordFOSUser1:changePassword
    _locale: fr
    _format: '%exim.theme.front.format%'
  requirements:
    _locale: fr
    _format: html|json
  options:
    expose: true

sonata_user_change_password:
  path: "/change-password.{_format}"
  methods: [GET,POST]
  defaults:
    _controller: ApplicationSonataUserBundle:ChangePasswordFOSUser1:changePassword
    _locale: fr
    _format: '%exim.theme.front.format%'
  requirements:
    _locale: fr
    _format: html|json
  options:
    expose: true
