lcdd_speaker_all:
    pattern: "/tous.{_format}"
    methods: "GET"
    defaults:
        _controller: ApplicationSonataUserBundle:ProfileFOSUser1:all
        _locale: fr
        _format: '%exim.theme.front.format%'
    requirements:
        _locale: fr
        _format: html|json
    options:
        expose: true

lcdd_speaker_get:
    pattern: "/{username}.{_format}"
    methods: "GET"
    defaults:
        _controller: ApplicationSonataUserBundle:ProfileFOSUser1:get
        username: 'me'
        _locale: fr
        _format: '%exim.theme.front.format%'
    requirements:
        _locale: fr
        _format: html|json
    options:
        expose: true

